version: "3"

services:
  backend:
    build:
      context: ./Backend

    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app/backend
    depends_on:
      - db
    links:
      - db:db
    networks:
      - mynetwork

  client:
    build:
      context: ./Client

    ports:
      - "3000:3000"
    volumes:
      - ./Client:/app/client
    networks:
      - mynetwork
    links:
      - backend

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
